### ISSUE TITLE
error No allowed database named null

### ISSUE THREAD

**Issue by leovafme** [yldio/pouch-websocket-sync#7]
in server.js

```
var PouchSync = require('pouch-websocket-sync');
var PouchDB = require('pouchdb');
var http = require('http');

var httpServer = http.createServer();
var server = PouchSync.createServer(httpServer, onRequest);
httpServer.listen(8028);

console.log('corriendo socket puerto: 8028');
function onRequest(credentials, dbName, cb) {
    if (credentials.token == 'some token') {
        console.log('esto es:',dbName)
        cb(null,new PouchDB(dbName));  
    } else {
        cb(new Error('not allowed'));
    }
};
```

---------------
in: main.js

```
var websocket = require('websocket-stream');
var PouchSync = require('pouch-websocket-sync');

var db = new PouchDB('prueba');

var client = PouchSync.createClient();
var sync = client.sync(db, {
  remoteName: 'prueba', // name remote db is known for
  credentials: { token: 'some token'} // arbitrary
});

client.connect('ws://localhost:8028');
```

use browserify main.js -o main-bundle.js

in index.html

```
<script src="//cdn.jsdelivr.net/pouchdb/6.1.0/pouchdb.min.js"></script>
<script src="/main-bundle.js"></script>
```

error: 
Uncaught (in promise) Error: No allowed database named null
    at errorForPayload (main-bundle.js:2878)
    at Writable._write (main-bundle.js:2857)
    at doWrite (main-bundle.js:10429)
    at writeOrBuffer (main-bundle.js:10418)
    at Writable.write (main-bundle.js:10356)
    at Duplexify._write (main-bundle.js:1535)
    at doWrite (main-bundle.js:5119)
    at writeOrBuffer (main-bundle.js:5108)
    at Duplexify.Writable.write (main-bundle.js:5046)
    at Stream.ondata (main-bundle.js:10701)

**Comment by carloslfu** [comment]
I am experimenting the same issue
